DROP DATABASE IF EXISTS ems_db;
CREATE DATABASE ems_db;
USE DATABASE ems_db;
DROP TABLE IF EXISTS department;
CREATE TABLE department(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    names VARCHAR(30) NOT NULL,
);
DROP TABLE IF EXISTS roles;

CREATE TABLE roles(
    id INT AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    salary DECIMAL NOT NULL,
    FOREIGN KEY(Department_id)
    REFERENCES Departments(id)
    ON DELETE SET NULL,
    PRIMARY KEY(id)
);
DROP TABLE IF EXISTS employee;
CREATE TABLE employee(
    id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    FOREIGN KEY(roles_id)
    REFERENCES roles(id)
    ON DELETE SET NULL,
);